[package]
name = "tcpreplay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "0.9.1"
pnet = "0.29.0"
clap = { version = "3.1.0", features = ["derive"] }
rand = "0.8.5"
